class Colors:
    def __init__(self):
        self.palette = {
            'Cool Gray 3': '7C93A0',
            'Chart Blue 3': 'A9CADF',
            'Chart Green 3': 'A9D5BC',
            'Chart Yellow 3': 'FEE0AE',
            'Chart Orange 3': 'FCCBAD',
            'Chart Red 3': 'F1AEB4',
            'Chart Purple 3': 'F8D7D9',
            'Cool Gray 4': '5C666D',
            'Chart Blue 4': 'A9CADF',
            'Chart Green 4': '7EC19B',
            'Chart Yellow 4': 'FED286',
            'Chart Orange 4': 'FCB285',
            'Chart Red 4': 'EA878F',
            'Chart Purple 4': 'F8D7D9',
            'Cool Gray 2': '93AEBE',
            'Chart Blue 2': 'D4E5EF',
            'Chart Green 2': 'D4EADD',
            'Chart Yellow 2': 'FEF0D6',
            'Chart Orange 2': 'FEE5D6',
            'Chart Red 2': 'F8D7D9',
            'Chart Purple 2': 'F8D7D9',
            'STATS': '276636',
            'Duplicates': '666666',
            'PIVOT': '594C80'
            }


countryCodes = {
    'us': 'USA',
    'ru': 'Russian Federation',
    'fr': 'France',
    'de': 'Germany',
    'it': 'Italy',
    'gb': 'UK',
    'mx': 'Mexico',
    'br': 'Brazil',
    'es': 'Spain',
    'tr': 'Turkey',
    'ua': 'Ukraine',
    'ca': 'Canada',
    'au': 'Australia',
    'in': 'India',
    'za': 'South Africa',
    'jp': 'Japan',
    'nl': 'Netherlands',
    'kz': 'Kazakhstan',
    'pl': 'Poland',
    'uz': 'Uzbekistan',
    'be': 'Belgium',
    'cl': 'Chile',
    'ro': 'Romania',
    'co': 'Colombia',
    'ch': 'Switzerland',
    'id': 'Indonesia',
    'ar': 'Argentina',
    'ng': 'Nigeria',
    'il': 'Israel',
    'tw': 'Taiwan',
    'hu': 'Hungary',
    'gr': 'Greece',
    'cz': 'Czechia',
    'at': 'Austria',
    'se': 'Sweden',
    'my': 'Malaysia',
    'pe': 'Peru',
    'pt': 'Portugal',
    'by': 'Belarus',
    'bg': 'Bulgaria',
    'az': 'Azerbaijan',
    'eg': 'Egypt',
    'sa': 'Saudi Arabia',
    'th': 'Thailand',
    'ma': 'Morocco',
    'kg': 'Kyrgyzstan',
    'ec': 'Ecuador',
    'kr': 'Korea',
    'dk': 'Denmark'
}
